name: Build source code on the develop branch
run-name: ${{ github.actor }} is building the source code

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_source:
    name: Build front-end source code
    runs-on: ubuntu-22.04
    env: 
      GENERATE_SOURCEMAP: false
      REACT_APP_PROXY_SERVER: ${{ vars.TEMP_REACT_APP_PROXY_SERVER }}
      REACT_APP_PROXY_LOG_LEVEL: "debug"
      BUILD_PATH: "./client-build"
      REACT_APP_VOTE_APP_DOMAIN: ${{ vars.TEMP_REACT_APP_VOTE_APP_DOMAIN }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build source code
        run: npm run build --if-present

      # - name: Test source code
      #   run: npm test --if-present

#   build_and_test_be:
#     name: Build and test back-end (bff) source code
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v3

#       - run: cd backend

#       - name: Setup NodeJS environment
#         uses: actions/setup-node@v3
#         with:
#           node-version: "16"
#           cache: "npm"

#       - name: Install dependencies
#         run: npm ci

#       - name: Build source code
#         run: npm run build --if-present

#       - name: Test source code
#         run: npm run test --if-present